apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
spec:
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongodb-express
        image: mongo-express
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: ME_CONFIG_MONGODB_SERVER
          value: mongodb
        - name: ME_CONFIG_BASICAUTH_USERNAME
          value: root
        - name: ME_CONFIG_BASICAUTH_PASSWORD
          value: admin
        ports:
        - containerPort: 8081
